# This is a sample build configuration for C++ â€“ Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: avilchess/grumpy-build:1.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - conan remote add conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz
          - conan install . --build
          - mkdir build
          - cd build
          - cmake ..
          - make all
          - make test